---
version: "3.7"
services:
  server:
    container_name: malice_flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8890:8890
    expose:
      - 8890
    volumes:
      - ./app.py:/var/www/cgi-bin/app.py
      - ./db.py:/var/www/cgi-bin/db.py
      - ./celery_init.py:/var/www/cgi-bin/celery_init.py
      - scan-data:/var/www/scans
      - scan-db:/var/www/db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8890
    depends_on:
      - redis
      - clamav
    command: ["./entrypoint.sh"]

  redis:
    image: redis
    container_name: redis

  clamav:
    image: clamav:latest
    container_name: malice_rest_clamav
    build:
      context: ./AVs/clamav
      dockerfile: Dockerfile
    volumes:
      - scan-malware:/malware

volumes:
  scan-db:
  scan-data:
  scan-malware:
